# Generated by Django 3.1.9 on 2021-06-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('celphone', models.CharField(max_length=50, verbose_name='telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='estado')),
                ('city', models.CharField(max_length=50, verbose_name='cidade')),
                ('district', models.CharField(max_length=50, verbose_name='bairro')),
                ('street', models.CharField(max_length=50, verbose_name='rua')),
                ('number', models.IntegerField(verbose_name='numero')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='seller.seller')),
            ],
        ),
    ]
