# Generated by Django 3.1.9 on 2021-06-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.address', verbose_name='endereco'),
        ),
    ]
