# Generated by Django 3.2.4 on 2021-06-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('phone', models.CharField(max_length=14, verbose_name='telefone')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='site')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(verbose_name='endpoint')),
                ('secret_key', models.CharField(max_length=255, verbose_name='secret_key')),
                ('api', models.URLField(verbose_name='api')),
                ('configurator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='marketplace.marketplace')),
            ],
        ),
    ]
